#ifndef CONSTANTS_H_

#define CONSTANTS_H_

#define OPCODE_RETURN 0
#define OPCODE_MEMCPY 1
#define OPCODE_MPIIRECV 2
#define OPCODE_MPIISEND 3
#define OPCODE_MPIWAITALL 4
#define OPCODE_NODEBARRIER 5
#define OPCODE_SETNUMCORES 6
#define OPCODE_SETNODERANK 7
#define OPCODE_REDUCE 8
#define OPCODE_MPISENDRECV 9
#define OPCODE_MPISEND 10
#define OPCODE_MPIRECV 11
#define OPCODE_LOCALMEM 12
#define OPCODE_MPIWAITANY 13
#define OPCODE_ATTACHED 14
#define OPCODE_REDUCE_WAIT 15
#ifdef GPU_ENABLED
#define OPCODE_GPUSYNCHRONIZE 16
#define OPCODE_GPUKERNEL 17
#endif

#define OPCODE_REDUCE_SUM_DOUBLE 0
#define OPCODE_REDUCE_SUM_LONG_INT 1
#define OPCODE_REDUCE_SUM_FLOAT 2
#define OPCODE_REDUCE_SUM_INT 3

#define ERROR_MALLOC -1
#define ERROR_SHMEM -2
#define ERROR_SYNTAX -3


#endif
